### ISSUE TITLE
Error message when someone posts a link

### ISSUE THREAD

**Issue by mirams** [BeepBoopHQ/starter-python-bot#10]
The starter bot posts an error message when someone posts a link in any slack channel it's listening to:

> :face_with_head_bandage: my maker didn't handle this error very well:
> 
> Traceback (most recent call last):
>   File "/src/bot/slack_bot.py", line 53, in start
>     event_handler.handle(event)
>   File "/src/bot/event_handler.py", line 17, in handle
>     self._handle_by_type(event['type'], event)
>   File "/src/bot/event_handler.py", line 26, in _handle_by_type
>     self._handle_message(event)
>   File "/src/bot/event_handler.py", line 38, in _handle_message
>     if not self.clients.is_message_from_me(event['user']):
> KeyError: 'user'

**Comment by randompi** [comment]
Should be fixed now with merge from PR #12

**Comment by mirams** [comment]
Yes, that has fixed it, thanks!
