### ISSUE TITLE
Bot fails to handle message events which do not contain a "user" field

### ISSUE THREAD

**Issue by thundergolfer** [BeepBoopHQ/starter-python-bot#11]
I noticed this bug when an incoming webhook to a channel that the bot was in cause the bot to crash. 
### Steps to reproduce
1. Fork this repo and install the bot as per instructions
2. Connect the bot to a team and invite it to a channel
3. Send a message into the channel without a _user_ field in the message payload.
### Expected Result

Bot ignores the message as it has not come from a user.
### Actual Result

Bot crashes with the following error trace output to the channel:

`Traceback (most recent call last):
  File "/src/bot/slack_bot.py", line 53, in start
    event_handler.handle(event)
  File "/src/bot/event_handler.py", line 16, in handle
    self._handle_by_type(event['type'], event)
  File "/src/bot/event_handler.py", line 25, in _handle_by_type
    self._handle_message(event)
  File "/src/bot/event_handler.py", line 37, in _handle_message
    if not self.clients.is_message_from_me(event['user']):
KeyError: 'user'`
### Related Issue - #10

I have checked the Slack API and the source code for my webhook and can be pretty sure that it is simply a matter of handling slack message events without a _user_ field by ignoring them correctly. The bot should first check if the _user_ key exists in the event object. If it doesn't then don't respond.

**Comment by randompi** [comment]
Should be fixed now with merge from PR #12
